<Project>
  <!-- Sdk properties and targets are imported manually to make the ____DependsOn properties work -->
  <!-- https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk#use-the-import-element-anywhere-in-your-project -->
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <!-- On OutDir vs OutputPath: https://github.com/dotnet/msbuild/blob/0a0959f86064b7922731df2978b051a744e75072/src/Tasks/Microsoft.Common.CurrentVersion.targets#L103-L133 -->
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <IsPublishable>false</IsPublishable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <ModBuildFolder>mod/SlugcatDriver</ModBuildFolder>
    <RainWorldDir>C:\Program Files (x86)\Steam\steamapps\common\Rain World</RainWorldDir>
    <GenerateDocumentationFile>true</GenerateDocumentationFile> <!--允许ReferenceTrimmer输出文档，这样它才能真的告诉你哪些没用上-->
  </PropertyGroup>

  <ItemGroup>
    <!-- 过时的依赖
        <Reference Include="HOOKS-Assembly-CSharp" HintPath="lib/HOOKS-Assembly-CSharp.dll" />
        <Reference Include="PUBLIC-Assembly-CSharp" HintPath="lib/PUBLIC-Assembly-CSharp.dll" />
    -->
    <Reference Include="HOOKS-Assembly-CSharp">
      <HintPath>$(RainWorldDir)\BepInEx\plugins\HOOKS-Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RainWorldDir)\RainWorld_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-All">
      <HintPath>$(RainWorldDir)\RainWorld_Data\Managed\*.dll</HintPath> <!--引用全部dll-->
      <Private>false</Private> <!--构建时不将dll打包到程序集内，避免法律问题-->
    </Reference>
    <Reference Include="Assembly-CSharp-Core">
      <HintPath>$(RainWorldDir)\RainWorld_Data\core\*.dll</HintPath> <!--引用全部dll-->
      <Private>false</Private> <!--构建时不将dll打包到程序集内，避免法律问题-->
    </Reference>
    <Reference Include="Assembly-CSharp-Utils">
      <HintPath>$(RainWorldDir)\RainWorld_Data\utils\PUBLIC-Assembly-CSharp.dll</HintPath>
      <Private>false</Private> <!--构建时不将dll打包到程序集内，避免法律问题-->
    </Reference>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.4.17" /> <!-- The version of BepInEx shipped with Rain World -->
    <PackageReference Include="UnityEngine.Modules" Version="2020.3.38" IncludeAssets="compile" /> <!-- The version of Unity shipped with Rain World -->
  </ItemGroup>

  <ItemGroup>
    <ModAssetFiles Include="assets/**/*" />
    <ModPluginFiles Include="$(TargetPath)" />
    <PackageReference Include="ReferenceTrimmer" Version="3.3.10" PrivateAssets="all" /> <!--告诉你哪些dll没用到-->
  </ItemGroup>

  <!--
    The files must be written under $(OutDir) for incremental cleaning to work, as files outside that directory get ignored by the clean: https://github.com/dotnet/msbuild/blob/0a0959f86064b7922731df2978b051a744e75072/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5580-L5602
    To understand Inputs, Outputs and FileWrites, read https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/MSBuildBestPractices.md#incremental-builds
  -->
  <Target Name="BuildModFolder"
      Inputs="@(ModAssetFiles);@(ModPluginFiles)"
      Outputs="@(ModAssetFiles->'$(OutDir)$(ModBuildFolder)/%(RecursiveDir)%(Filename)%(Extension)');@(ModPluginFiles->'$(OutDir)$(ModBuildFolder)/plugins/%(Filename)%(Extension)')">
    <Copy SourceFiles="@(ModAssetFiles)" DestinationFolder="$(OutDir)$(ModBuildFolder)/%(RecursiveDir)" />
    <Copy SourceFiles="@(ModPluginFiles)" DestinationFolder="$(OutDir)$(ModBuildFolder)/plugins" />
    <ItemGroup>
      <FileWrites Include="@(ModAssetFiles->'$(OutDir)$(ModBuildFolder)/%(RecursiveDir)%(Filename)%(Extension)');@(ModPluginFiles->'$(OutDir)$(ModBuildFolder)/plugins/%(Filename)%(Extension)')" />
    </ItemGroup>
  </Target>
  <Target Name="DeployMod" AfterTargets="Build">
    <!--自动覆盖旧的模组文件夹-->
    <ItemGroup>
      <ModFiles Include="$(OutDir)$(ModBuildFolder)\**\*" />
    </ItemGroup>

    <Copy SourceFiles="@(ModFiles)"
          DestinationFolder="C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\StreamingAssets\mods\SlugcatDriver\%(RecursiveDir)"
          SkipUnchangedFiles="true"
          OverwriteReadOnlyFiles="true" />
  </Target>


  <!-- The ____DependsOn properties only work when defined after importing the Sdk targets -->
  <!-- https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process#override-dependson-properties -->
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <!-- https://github.com/dotnet/msbuild/pull/5499 -->
    <IncrementalCleanDependsOn>
      BuildModFolder;
      $(IncrementalCleanDependsOn)
    </IncrementalCleanDependsOn>
  </PropertyGroup>

</Project>
